version: "3"

networks:
  dev-frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.1.0/24
  dev-backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.2.0/23

services:
  dev-db:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3307
    networks:
      dev-backend:
        ipv4_address: 172.10.3.2
    env_file:
      - ./development.env
  dev-www:
    build: ./www
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html/
    networks:
      dev-backend:
        ipv4_address: 172.10.2.2
      dev-frontend:
        ipv4_address: 172.10.1.2
    depends_on:
      - dev-db
    env_file:
      - ./development.env
